### ISSUE TITLE
mean cmd not working

### ISSUE THREAD

**Issue by suzet** [meanjs/mean#1416]
**mean init <appName> working and it create mean app but at the end i got error message.** 

> mean@0.6.1 prepublish d:\mean_stack\myFirstApp
> npm run snyk-protect

> mean@0.6.1 snyk-protect d:\mean_stack\myFirstApp
> snyk protect

ENOENT: no such file or directory, open 'd:\mean_stack\myFirstApp\node_modules\n
pm\node_modules\glob\node_modules\minimatch\.snyk-npm:minimatch:20160620.flag'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "d:\\mean_stack\\myFirstApp\
\node_modules\\npm\\bin\\npm-cli.js" "run" "snyk-protect"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! mean@0.6.1 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.6.1 snyk-protect script 'snyk protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     snyk protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\mean_stack\myFirstApp\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! mean@0.6.1 prepublish: `npm run snyk-protect`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mean@0.6.1 prepublish script 'npm run snyk-protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run snyk-protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     d:\mean_stack\myFirstApp\npm-debug.log

**and when gulp run its it opening on 3000 port, 
then when i try to run mean status or mean package <packagename> throws npm error i.e.**

module.js:442
    throw err;
    ^

Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Thenextcoders\AppData\Roaming\npm\node_modul
es\mean-cli\lib\cli.js:5:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by marianoqueirel** [comment]
If you working with Master Branch The version recommended for the project node is 4.x.x 
If you working with the Versión 0.4.x of MEAN, recommended for the project node is 0.12.x. 

It is correct what I say @lirantal @mleanos  ?

**Comment by shanavas786** [comment]
looks like a [mean.io](http:/mean.io) issue.

**Comment by suzet** [comment]
yes it is mean.io problem
