### ISSUE TITLE
npm install fails with "error: ‘class v8::Object’ has no member named ‘ForceSet’" on node-sass with v10.15.1

### ISSUE THREAD

**Issue by cirosantilli** [meanjs/mean#2010]
094bae534b6c10602978efc2fe8ebdb51b29c57e Ubuntu 18.10.

It works on nodejs v8.11.1 though.

One of the modules depends on node-sass, but the required version of node-saas does not support newer node, the error observed is the same as: https://github.com/sass/node-sass/issues/2549

npm list contains:

```
─┬ gulp-sass@3.1.0
│ ├── gulp-util@3.0.8 deduped
│ ├── lodash.clonedeep@4.5.0
│ ├─┬ node-sass@4.5.3
```

Would also be good to specify the supported nodejs version if not already done, idealy with `.nvmrc`.

**Comment by xiandalisay** [comment]
Hi @cirosantilli Got any updates? I also experience this issue.

**Comment by cirosantilli** [comment]
@xiandalisay nope! I'll post if I do. I just felt https://github.com/balderdashy/sails might be a better idea, this is too bare for me :-)

**Comment by Zenoo** [comment]
Same issue here.

Node v10.16.0

**Comment by xiandalisay** [comment]
@Zenoo It would be better to downgrade to v8 as well.

**Comment by ilanbiala** [comment]
Can you try now with master?
